import { Inter } from 'next/font/google'
import './globals.css'

const syne = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'GoPaddi',
  description: 'Generated by create next app',
}

function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${syne.className} flex  justify-center   `}>{children}</body>
    </html>
  )
}
export default RootLayout;
